apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gasinstorestate
spec:
  type: state.mongodb
  version: v1
  scopes:
    - dispatch_api
  metadata:
  - name: host
    value: dispatch_stateserver:27017
  - name: databaseName
    value: "dispatch"
  - name: collectionName
    value: "gisCollection"