apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: inboxstate
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6380
    - name: redisPassword
      value: "S3cr3tPassw0rd!"
    - name: redisDB
      value: "2"
scopes:
  - dispatchapi