apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: inboxstate
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: dispatch_stateserver:27017
  - name: databaseName
    value: "dispatch"
  - name: collectionName
    value: "inboxCollection"
  - name: params
    value: "?replicaSet=rs0"