apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dispatch_state
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: stateserver:27017
  - name: databaseName
    value: "dispatch"
  - name: collectionName
    value: "dispatchCollection"
  - name: params
    value: "?replicaSet=rs0"
  # - name: outboxPublishPubsub # pubsub component name to use for outbox publish
  #   value: "dispatch_pubsub"
  # - name: outboxPublishTopic # Required
  #   value: "flowint_outbox"
  # - name: outboxDiscardWhenMissingState #
  #   value: false