apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outboxstate
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost port=5432 database=dispatch user=sa password=SomePassword sslmode=disable connect_timeout=10"
  - name: tableName
    value: "dispatchCollection"
  - name: metadataTableName
    value: "dispatchCollectionmetadata" 