apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: plantstate
spec:
  type: state.mongodb
  version: v1
  scopes:
    - plant_api
  metadata:
  - name: host
    value: plant_stateserver:27017
  - name: databaseName
    value: "plant"
  - name: collectionName
    value: "plantCollection"