apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gasinstorestate
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=dispatch_stateserver;port=5432;database=dispatch;user id='sa';password='SomePassword'"
  - name: tableName
    value: "gisCollection"