#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: gasinstorestate
#spec:
#  type: state.postgresql
#  version: v1
#  metadata:
#  - name: connectionString
#    value: "host=localhost port=5432 database=dispatch user=sa password=SomePassword sslmode=disable connect_timeout=10"
#  - name: tableName
#    value: "gisCollection"
#  - name: metadataTableName
#    value: "gisCollectionmetadata" 

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gasinstorestate
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6380
    - name: redisPassword
      value: ""
    - name: redisDB
      value: "1"