apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outboxstate
spec:
  type: state.mongodb
  version: v1
  scopes:
    - dispatch_api
  metadata:
  - name: host
    value: dispatch_stateserver:27017
  - name: databaseName
    value: "dispatch"
  - name: collectionName
    value: "outboxCollection"
  - name: params
    value: "?replicaSet=rs0"
  # - name: outboxPublishPubsub # pubsub component name to use for outbox publish
  #   value: "dispatch_pubsub"
  # - name: outboxPublishTopic # Required
  #   value: "flowint_outbox"
  # - name: outboxDiscardWhenMissingState #
  #   value: false