apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: plantstate
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=localhost port=5432 database=dispatch user=sa password=SomePassword sslmode=disable connect_timeout=10"
    - name: tableName
      value: "plantCollection"
    - name: metadataTableName
      value: "plantCollectionmetadata"

# cosmosdb component statestore
#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: plantstate
#spec:
#  type: state.azure.cosmosdb
#  version: v1
#  metadata:
#    - name: url
#      value: ""
#    - name: masterkey
#      value: ""
#    - name: database
#      value: "plant"
#    - name: collection
#      value: "plantstate"
