version: '3.4'

services:
  MissionCriticalDemo.DispatchApi:
    image: ${DOCKER_REGISTRY-}missioncriticaldemo.dispatchapi
    build:
      context: .
      dockerfile: MissionCriticalDemo.DispatchApi/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - mission-critical-network
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  MissionCriticalDemo.PlantApi:
    image: ${DOCKER_REGISTRY-}missioncriticaldemo.plantapi
    build:
      context: .
      dockerfile: MissionCriticalDemo.PlantApi/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - mission-critical-network


networks:
    mission-critical-network:
